// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lamlai.data;

#nullable disable

namespace lamlai.Migrations
{
    [DbContext(typeof(myDBcontext))]
    [Migration("20230201073333_Dbloai")]
    partial class Dbloai
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lamlai.data.HangHoa", b =>
                {
                    b.Property<Guid>("Mahh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("dongia")
                        .HasColumnType("float");

                    b.Property<byte>("giamgia")
                        .HasColumnType("tinyint");

                    b.Property<int?>("maloai")
                        .HasColumnType("int");

                    b.Property<string>("tenhh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Mahh");

                    b.HasIndex("maloai");

                    b.ToTable("hangHoa");
                });

            modelBuilder.Entity("lamlai.data.Loai", b =>
                {
                    b.Property<int>("maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maloai"), 1L, 1);

                    b.Property<string>("matenloai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maloai");

                    b.ToTable("loai");
                });

            modelBuilder.Entity("lamlai.data.HangHoa", b =>
                {
                    b.HasOne("lamlai.data.Loai", "loai")
                        .WithMany("HangHoas")
                        .HasForeignKey("maloai");

                    b.Navigation("loai");
                });

            modelBuilder.Entity("lamlai.data.Loai", b =>
                {
                    b.Navigation("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
