// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lamlai.data;

#nullable disable

namespace lamlai.Migrations
{
    [DbContext(typeof(myDBcontext))]
    [Migration("20230202071013_a")]
    partial class a
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lamlai.data.DonHang", b =>
                {
                    b.Property<Guid>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tinhtrang")
                        .HasColumnType("int");

                    b.Property<string>("diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nguoinhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDH");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("lamlai.data.DonHangChitiet", b =>
                {
                    b.Property<Guid>("MaDH")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Mahh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Dongia")
                        .HasColumnType("float");

                    b.Property<int>("Soluongton")
                        .HasColumnType("int");

                    b.Property<byte>("giamgia")
                        .HasColumnType("tinyint");

                    b.HasKey("MaDH", "Mahh");

                    b.HasIndex("Mahh");

                    b.ToTable("ChitietDonHang", (string)null);
                });

            modelBuilder.Entity("lamlai.data.HangHoa", b =>
                {
                    b.Property<Guid>("Mahh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("dongia")
                        .HasColumnType("float");

                    b.Property<byte>("giamgia")
                        .HasColumnType("tinyint");

                    b.Property<int?>("maloai")
                        .HasColumnType("int");

                    b.Property<string>("tenhh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Mahh");

                    b.HasIndex("maloai");

                    b.ToTable("hangHoa");
                });

            modelBuilder.Entity("lamlai.data.Loai", b =>
                {
                    b.Property<int>("maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("maloai"), 1L, 1);

                    b.Property<string>("matenloai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maloai");

                    b.ToTable("loai");
                });

            modelBuilder.Entity("lamlai.data.DonHangChitiet", b =>
                {
                    b.HasOne("lamlai.data.DonHang", "DonHang")
                        .WithMany("DonHangChitiets")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DonHangCT_DonHang");

                    b.HasOne("lamlai.data.HangHoa", "HangHoa")
                        .WithMany("DonHangChitiets")
                        .HasForeignKey("Mahh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DonHangCT_HangHoa");

                    b.Navigation("DonHang");

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("lamlai.data.HangHoa", b =>
                {
                    b.HasOne("lamlai.data.Loai", "loai")
                        .WithMany("HangHoas")
                        .HasForeignKey("maloai");

                    b.Navigation("loai");
                });

            modelBuilder.Entity("lamlai.data.DonHang", b =>
                {
                    b.Navigation("DonHangChitiets");
                });

            modelBuilder.Entity("lamlai.data.HangHoa", b =>
                {
                    b.Navigation("DonHangChitiets");
                });

            modelBuilder.Entity("lamlai.data.Loai", b =>
                {
                    b.Navigation("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
