// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Them_sua_xoa.Data;

namespace Them_sua_xoa.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230110073916_AddtbLoai")]
    partial class AddtbLoai
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Them_sua_xoa.Data.HangHoa", b =>
                {
                    b.Property<Guid>("maHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("donGia")
                        .HasColumnType("float");

                    b.Property<byte>("giamGia")
                        .HasColumnType("tinyint");

                    b.Property<int?>("maLoai")
                        .HasColumnType("int");

                    b.Property<string>("moTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maHang");

                    b.HasIndex("maLoai");

                    b.ToTable("HangHoas");
                });

            modelBuilder.Entity("Them_sua_xoa.Data.Loai", b =>
                {
                    b.Property<int>("maLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("tenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("maLoai");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("Them_sua_xoa.Data.HangHoa", b =>
                {
                    b.HasOne("Them_sua_xoa.Data.Loai", "Loai")
                        .WithMany("HangHoas")
                        .HasForeignKey("maLoai");

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("Them_sua_xoa.Data.Loai", b =>
                {
                    b.Navigation("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
