// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Them_sua_xoa.Data;

namespace Them_sua_xoa.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230110070644_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Them_sua_xoa.Data.HangHoa", b =>
                {
                    b.Property<Guid>("maHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("donGia")
                        .HasColumnType("float");

                    b.Property<byte>("giamGia")
                        .HasColumnType("tinyint");

                    b.Property<string>("moTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("maHang");

                    b.ToTable("HangHoas");
                });
#pragma warning restore 612, 618
        }
    }
}
